import defaultExport from "module-name-1";
import * as name from "module-name-2";
import { export1 } from "module-name-3";
import { export1 as alias1 } from "module-name-4";
import { default as alias } from "module-name-5";
import { export1, export2 } from "module-name-6";
import { export1, export2 as alias2, /* … */ } from "module-name-7";
import { "string name" as alias } from "module-name-8";
import defaultExport, { export1, /* … */ } from "module-name-9";
import defaultExport, * as name from "module-name-10";
import "module-name-11";
